#
#  conf.py
#
# This file is part of NEST GPU.
#
# Copyright (C) 2021 The NEST Initiative
#
# NEST GPU is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# NEST GPU is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NEST GPU.  If not, see <http://www.gnu.org/licenses/>.
# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use str(Path().resolve()) to make it absolute.
#

import sys
import json
from pathlib import Path
sys.path.insert(0, str(Path().resolve()))

source_dir = Path(__file__).resolve().parent.resolve()

# Add the extension modules to the path
sys.path.append(str(source_dir / "_ext"))
doc_build_dir = source_dir / "models"

print("doc_build_dir", str(doc_build_dir))
print("source_dir", str(source_dir))


# -- Project information -----------------------------------------------------

project = u'NEST GPU user documentation'
copyright = u'2021, nest-gpu'
author = u'nest-gpu'

# The full version, including alpha/beta/rc tags
release = '1'

source_suffix = '.rst'
master_doc = 'index'

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.intersphinx',
    'sphinx.ext.mathjax',
    'sphinx.ext.napoleon',
    'sphinx_design',
    'sphinx_carousel.carousel',
    'sphinx_copybutton',
    'notfound.extension',
    'nbsphinx',
    'sphinxcontrib.bibtex',
]

bibtex_bibfiles = ['refs.bib']
bibtex_default_style = 'unsrt'

copybutton_prompt_text = ">>> "
# The output lines will not be copied if set to True
copybutton_only_copy_prompt_lines = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['templates']

# The language for content autogenerated by Sphinx.
language = 'en'

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'manni'

# add numbered figure link
numfig = True

numfig_secnum_depth = 2
numfig_format = {'figure': 'Figure %s', 'table': 'Table %s', 'code-block': 'Code Block %s'}

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [
    '**.ipynb_checkpoints',
    '.DS_Store',
    'Thumbs.db',
]

# Only projects that are actually cross-referenced from the documentation are
# listed here: every entry causes an inventory download on each build. Add a
# mapping back when a :doc: or :ref: role starts pointing at that project.
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'nest': ('https://nest-simulator.readthedocs.io/en/latest/', None),
    'nestml': ('https://nestml.readthedocs.io/en/latest/', None),
}

# sphinx-material puts functions into html_context, which Sphinx cannot pickle
# for its configuration cache. The resulting warning is harmless and cannot be
# fixed from here.
suppress_warnings = ['config.cache']


# Extract documentation from header files in src/

from extractor_userdocs import relative_glob, ExtractUserDocs

def config_inited_handler(app, config):
    ExtractUserDocs(
        listoffiles=relative_glob("../../src/*.h", basedir=source_dir),
        basedir=source_dir,
        outdir=str(doc_build_dir)
    )

def setup(app):
    # for events see
    # https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx-core-events
    app.connect('config-inited', config_inited_handler)

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_material'
html_title = 'NEST GPU Documentation'

html_show_sphinx = False
html_show_copyright = False
# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['static']

html_css_files = [
    'css/custom.css',
    'css/pygments.css',
]

html_logo =  'static/img/logos/nestgpu-logo.png'

html_favicon = 'static/img/nest_favicon.ico'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    # Specify a base_url used to generate sitemap.xml.
    'base_url': 'https://nest-gpu.readthedocs.io/en/latest/',
    'html_minify': False,
    'html_prettify': False,
    'css_minify': True,
    # Set the color and the accent color
    'color_primary': 'orange',
    'color_accent': 'white',
    'theme_color': 'ff6633',
    'master_doc': False,
    # Set the repo location to get a badge with stats
    'repo_url': 'https://github.com/nest/nest-gpu/',
    'repo_name': 'NEST GPU',
    'nav_links': [{'href': 'index', 'internal': True, 'title': 'NEST GPU docs home'}],
    # Visible levels of the global TOC; -1 means unlimited
    'globaltoc_depth': 1,
    # If False, expand all TOC entries
    'globaltoc_collapse': True,
    # If True, show hidden TOC entries
    'globaltoc_includehidden': True,
    'version_dropdown': False,
}

html_sidebars = {'**': ['logo-text.html', 'globaltoc.html', 'localtoc.html', 'searchbox.html']}